name: Caller Workflow

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  call_reusable_workflow:
    uses: jcroyoaun/reusable-workflow-dest/.github/workflows/reusable-workflow-concurrency.yml@main
