name: Caller Workflow

on:
  push:
    branches: [ main ]

jobs:
  call_reusable_workflow:
    strategy:
      matrix:
        environment: [prod, stage, stage_ca, prod_ca]
        experience: [old, new]
    uses: dblinkzz/reusable-workflow-dest/.github/workflows/reusable-workflow-concurrency.yaml@main
    with:
      environment: ${{ matrix.environment }}
      experience: ${{ matrix.experience }}
