name: Caller Workflow

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  call_reusable_workflow:
    uses: dblinkzz/reusable-workflow-dest/.github/workflows/reusable-workflow-concurrency.yaml@main
